# Generated by Django 5.1.6 on 2025-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_game_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('STR', 'Strategy'), ('RPG', 'Role-Playing Game'), ('ACT', 'Action')], db_index=True, default='STR', max_length=3),
        ),
    ]
